### ISSUE TITLE
求demo里背景切换效果的实现方式

### ISSUE THREAD

**Issue by yinyanfr** [BoatingZeng/boatgal#1]

**Comment by BoatingZeng** [comment]
在 lib/galRenderer/effect 里。详细说明可以看每个目录下的design.md。

**Comment by yinyanfr** [comment]
好吧，这个createjs挺有意思的

**Comment by yinyanfr** [comment]
说来大哥哥要不要加入更新姬的同人社团（筹），虽然目前只有两个人

**Comment by BoatingZeng** [comment]
怎样联系？我只有QQ:945467442。你们是萌娘百科的吗？我加了一个叫“里萌娘网程序技术部”的群。

**Comment by yinyanfr** [comment]
这个只是个人项目，大哥哥加这个群吧 211131525
